[package]
name = "acorn"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
smallvec = "*"
cranelift = "0.33.0"
cranelift-frontend = "0.33.0"